services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DB_HOST=${{Postgres.PGHOST}}
      - DB_PORT=${{Postgres.PGPORT}}
      - DB_NAME=${{Postgres.PGDATABASE}}
      - DB_USER=${{Postgres.PGUSER}}
      - DB_PASSWORD=${{Postgres.PGPASSWORD}}
      - JUDGE_HOST=your-mini-judge-url.railway.app
      - JUDGE_PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mini_competition_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${{Backend.RAILWAY_PUBLIC_DOMAIN}}
    restart: unless-stopped
