services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - shared-network
    environment:
      - FLASK_ENV=development
      - JWT_SECRET=your-secret-key-change-this
      - JWT_EXPIRATION=3600
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mini_competition_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JUDGE_HOST=mini-judge
      - JUDGE_PORT=3000
    volumes:
      - ./backend:/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mini_competition_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true
    name: mini-competition-network

volumes:
  postgres_data: 