[build]
builder = "dockerfile"
dockerfilePath = "docker-compose.yaml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production", FLASK_ENV = "production" }
