[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
  FLASK_ENV = "production", 
  FLASK_DEBUG = "False",
  JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production",
  JUDGE_HOST = "your-mini-judge-url.railway.app",
  JUDGE_PORT = "3000",
  DB_HOST = "${{Postgres.PGHOST}}",
  DB_PORT = "${{Postgres.PGPORT}}",
  DB_NAME = "${{Postgres.PGDATABASE}}",
  DB_USER = "${{Postgres.PGUSER}}",
  DB_PASSWORD = "${{Postgres.PGPASSWORD}}"
}
